version: "3"

vars:
  VERSION: "1.0-SNAPSHOT"
  SOLVER_JAR_FILE: "solver/target/aoc-solver-{{.VERSION}}-jar-with-dependencies.jar"
  GENERATOR_JAR_FILE: "generator/target/aoc-generator-{{.VERSION}}-jar-with-dependencies.jar"

tasks:
  build:
    desc: Build the project
    cmds:
      - mvn verify
  install:
    desc: Install the project to use the solve
    cmds:
      - mvn install
  quick-build:
    desc: Build the solver without executing the tests
    cmds:
      - mvn -pl solver package -DskipTests
    generates:
      - "{{.JAR_FILE}}"
  run-day-*-*-*:
    dotenv:
      - .env
    desc: Run the solver for a given day/part
    vars:
      YEAR: "{{index .MATCH 0}}"
      DAY: "{{index .MATCH 1}}"
      PART: "{{index .MATCH 2}}"
    deps:
      - quick-build
    cmds:
      - java -jar {{.SOLVER_JAR_FILE}} {{.YEAR}} {{.DAY}} {{.PART}}
  run-test-*-*-*:
    desc: Runt the tests for a given day/part
    vars:
      YEAR: "{{index .MATCH 0}}"
      DAY: "{{index .MATCH 1}}"
      PART: "{{index .MATCH 2}}"
    cmds:
      - mvn test -Dtest=eu.pierrebeitz.aoc._{{.YEAR}}.Day{{.DAY}}Puzzle{{.PART}}Test
  generate-day-*-*-*-*:
    desc: Generate the day's puzzle
    vars:
      YEAR: "{{index .MATCH 0}}"
      DAY: "{{index .MATCH 1}}"
      PART: "{{index .MATCH 2}}"
      OUTPUT: "{{index .MATCH 3}}"
    cmds:
      - java -jar {{.GENERATOR_JAR_FILE}} --year {{.YEAR}} --day {{.DAY}} --part {{.PART}} --output {{.OUTPUT}}
  fmt:
    desc: Format the code of the project
    cmds:
      - mvn spotless:apply