version: "3"

vars:
  VERSION: "1.0-SNAPSHOT"
  JAR_FILE: "target/aoc-{{.VERSION}}-jar-with-dependencies.jar"

tasks:
  build:
    desc: Build the project
    cmds:
      - mvn verify
  quick-build:
    desc: Build the project without executing the tests
    cmds:
      - mvn package -DskipTests
    generates:
      - "{{.JAR_FILE}}"
  run-day-*-*-*:
    desc: Run the solver for a given day/part
    vars:
      YEAR: "{{index .MATCH 0}}"
      DAY: "{{index .MATCH 1}}"
      PART: "{{index .MATCH 2}}"
    deps:
      - quick-build
    cmds:
      - java -jar {{.JAR_FILE}} {{.YEAR}} {{.DAY}} {{.PART}}
  run-test-*-*-*:
    desc: Runt the tests for a given day/part
    vars:
      YEAR: "{{index .MATCH 0}}"
      DAY: "{{index .MATCH 1}}"
      PART: "{{index .MATCH 2}}"
    cmds:
      - mvn test -Dtest=eu.pierrebeitz.aoc._{{.YEAR}}.Day{{.DAY}}Puzzle{{.PART}}Test
